paths:
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  model_dir: "models"

data_settings:
  target_city: "jaipur"   
  forecast_days: 7   

model_settings:
  test_size: 0.2     
  random_state: 42